[package]
name = "queries_recurse"
type = "bin"
authors = [""]

[dependencies]
cheon_stehle = { path = "../../libs/cheon_stehle" }
bignum = { tag = "v0.5.4", git = "https://github.com/noir-lang/noir-bignum" }
